### ISSUE TITLE
BuildDeploy stage issue

### ISSUE THREAD

**Issue by harishchitipothu** [getcft/aws-serverless-code-pipeline-cf-template#6]
Getting an error at BuildDeploy stage - error is {COMMAND_EXECUTION_ERROR: Error while executing command: serverless deploy --stage $env --package $CODEBUILD_SRC_DIR/artifacts/$env -v. Reason: exit status 1}

**Comment by nethacker** [comment]
Please try the newest version, I have changed how I handle this section.
